apiVersion: grizzly.grafana.com/v1alpha1
kind: Dashboard
metadata:
  folder: general
  name: cpu-usage
spec:
  schemaVersion: 2023041201
  tags:
    - Linuxfabrik
    - Icinga
    - Grizzly
  time:
    from: now-90d
    to: now
  timepicker:
    hidden: false
    refresh_intervals:
    - 1m
  timezone: browser
  title: CPU Usage
  uid: linuxfabrik-monitoring-plugins-cpu-usage
  editable: true
  liveNow: true
  refresh: 1m
  templating:
    list:
    - hide: 2
      label: Command
      name: command
      query: cmd-check-cpu-usage
      type: constant
    - label: Hostname
      name: hostname
      query: SHOW TAG VALUES FROM "cmd-check-cpu-usage" WITH KEY = "hostname"
      refresh: 2
      sort: 1
      type: query

  panels:

  - title: CPU Usage - Percentages
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 0
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          lineInterpolation: smooth
          spanNulls: true
        decimals: 0
        max: 110
        min: 0
        unit: percent
      overrides:
      - __systemRef: hideSeriesFrom
        matcher:
          id: byNames
          options:
            mode: exclude
            names:
            - cpu-usage
            prefix: 'All except:'
        properties:
        - id: custom.hideFrom
          value:
            viz: true
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: cpu-usage
      refId: cpu-usage
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: CPU Usage
      - condition: AND
        key: metric
        operator: '='
        value: cpu-usage

    - alias: guest
      refId: guest
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: CPU Usage
      - condition: AND
        key: metric
        operator: '='
        value: guest

    - alias: guest_nice
      refId: guest_nice
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: CPU Usage
      - condition: AND
        key: metric
        operator: '='
        value: guest_nice

    - alias: iowait
      refId: iowait
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: CPU Usage
      - condition: AND
        key: metric
        operator: '='
        value: iowait


    - alias: irq
      refId: irq
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: CPU Usage
      - condition: AND
        key: metric
        operator: '='
        value: irq

    - alias: nice
      refId: nice
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: CPU Usage
      - condition: AND
        key: metric
        operator: '='
        value: nice

    - alias: soft_irq
      refId: soft_irq
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: CPU Usage
      - condition: AND
        key: metric
        operator: '='
        value: soft_irq

    - alias: steal
      refId: steal
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: CPU Usage
      - condition: AND
        key: metric
        operator: '='
        value: steal

    - alias: system
      refId: system
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: CPU Usage
      - condition: AND
        key: metric
        operator: '='
        value: system

    - alias: user
      refId: user
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: CPU Usage
      - condition: AND
        key: metric
        operator: '='
        value: user


  - title: CPU Usage - Interrupts and Switches
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 12
      y: 0
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          lineInterpolation: smooth
          spanNulls: true
        decimals: 0
        min: 0
        unit: short

    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: ctx_switches
      refId: ctx_switches
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
        - params: []
          type: non_negative_difference
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: CPU Usage
      - condition: AND
        key: metric
        operator: '='
        value: ctx_switches

    - alias: interrupts
      refId: interrupts
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
        - params: []
          type: non_negative_difference
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: CPU Usage
      - condition: AND
        key: metric
        operator: '='
        value: interrupts

    - alias: soft_interrupts
      refId: soft_interrupts
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
        - params: []
          type: non_negative_difference
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: CPU Usage
      - condition: AND
        key: metric
        operator: '='
        value: soft_interrupts
