---
variants:
  - windows

overwrites:
  '["ServiceTemplate"]["tpl-service-service-windows"]["enable_notifications"]': false
  '["ServiceTemplate"]["tpl-service-service-windows"]["vars"]["service_windows_status"]': ['running']
