apiVersion: grizzly.grafana.com/v1alpha1
kind: Dashboard
metadata:
  folder: linuxfabrik-monitoring-plugins
  name: apache-httpd-status
spec:
  schemaVersion: 2023041201
  tags:
    - Linuxfabrik
    - Icinga
    - Grizzly
  time:
    from: now-90d
    to: now
  timepicker:
    hidden: false
    refresh_intervals:
    - 1m
  timezone: browser
  title: Apache httpd Status
  uid: linuxfabrik-monitoring-plugins-apache-httpd-status
  editable: true
  liveNow: true
  refresh: 1m
  templating:
    list:
    - hide: 2
      label: Command
      name: command
      query: cmd-check-apache-httpd-status
      type: constant
    - label: Hostname
      name: hostname
      query: SHOW TAG VALUES FROM "cmd-check-apache-httpd-status" WITH KEY = "hostname"
      refresh: 2
      sort: 1
      type: query

  panels:

  - title: Apache httpd Status - Accesses
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 0
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          lineInterpolation: smooth
          spanNulls: true
        decimals: 0
        min: 0
        unit: short
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: Accesses
      refId: Accesses
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: Accesses


  - title: Apache httpd Status - Bytes sent
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 12
      y: 0
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          lineInterpolation: smooth
          spanNulls: true
        decimals: 0
        min: 0
        unit: bytes
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: Bytes
      refId: Bytes
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: Bytes


  - title: Apache httpd Status - Conns
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 8
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          lineInterpolation: smooth
          spanNulls: true
        decimals: 0
        min: 0
        unit: short
      overrides:
      - __systemRef: hideSeriesFrom
        matcher:
          id: byNames
          options:
            mode: exclude
            names:
            - ConnsTotal
            prefix: 'All except:'
        properties:
        - id: custom.hideFrom
          value:
            viz: true
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: ConnsAsyncClosing
      refId: ConnsAsyncClosing
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: ConnsAsyncClosing

    - alias: ConnsAsyncKeepAlive
      refId: ConnsAsyncKeepAlive
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: ConnsAsyncKeepAlive

    - alias: ConnsAsyncWriting
      refId: ConnsAsyncWriting
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: ConnsAsyncWriting

    - alias: ConnsTotal
      refId: ConnsTotal
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: ConnsTotal


  - title: Apache httpd Status - Load
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 12
      y: 8
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          lineInterpolation: smooth
          spanNulls: true
        decimals: 2
        min: 0
        unit: short
      overrides:
      - __systemRef: hideSeriesFrom
        matcher:
          id: byNames
          options:
            mode: exclude
            names:
            - Load15
            prefix: 'All except:'
        properties:
        - id: custom.hideFrom
          value:
            viz: true
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: Load1
      refId: Load1
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: Load1

    - alias: Load5
      refId: Load5
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: Load5

    - alias: Load15
      refId: Load15
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: Load15


  - title: Apache httpd Status - Workers Aggregated
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 16
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          lineInterpolation: smooth
          spanNulls: true
        decimals: 0
        min: 0
        unit: none
      overrides:
      - __systemRef: hideSeriesFrom
        matcher:
          id: byNames
          options:
            mode: exclude
            names:
            - BusyWorkers
            - IdleWorkers
            prefix: 'All except:'
        properties:
        - id: custom.hideFrom
          value:
            viz: true
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: BusyWorkers
      refId: BusyWorkers
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: BusyWorkers

    - alias: IdleWorkers
      refId: IdleWorkers
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: IdleWorkers

    - alias: TotalWorkers
      refId: TotalWorkers
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: TotalWorkers


  - title: Apache httpd Status - Workers Scoreboard
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 12
      y: 16
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          lineInterpolation: smooth
          spanNulls: true
        decimals: 0
        min: 0
        unit: none
      overrides:
      - __systemRef: hideSeriesFrom
        matcher:
          id: byNames
          options:
            mode: exclude
            names:
            - workers_replying
            - workers_waiting
            prefix: 'All except:'
        properties:
        - id: custom.hideFrom
          value:
            viz: true
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: workers_closing
      refId: workers_closing
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: workers_closing

    - alias: workers_dns
      refId: workers_dns
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: workers_dns

    - alias: workers_finishing
      refId: workers_finishing
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: workers_finishing

    - alias: workers_free
      refId: workers_free
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: workers_free

    - alias: workers_idle
      refId: workers_idle
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: workers_idle

    - alias: workers_keepalive
      refId: workers_keepalive
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: workers_keepalive

    - alias: workers_logging
      refId: workers_logging
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: workers_logging

    - alias: workers_reading
      refId: workers_reading
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: workers_reading

    - alias: workers_replying
      refId: workers_replying
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: workers_replying

    - alias: workers_starting
      refId: workers_starting
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: workers_starting

    - alias: workers_waiting
      refId: workers_waiting
      groupBy:
      - params:
        - $interval
        type: time
      measurement: /^$command$/
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '=~'
        value: /^$hostname$/
      - condition: AND
        key: service
        operator: '='
        value: Apache httpd Status
      - condition: AND
        key: metric
        operator: '='
        value: workers_waiting
