---
variants:
  - linux
  - no-agent

overwrites:
  '["Command"]["cmd-check-csv-values"]["timeout"]': 30
  '["ServiceTemplate"]["tpl-service-csv-values"]["check_interval"]': 300
  '["ServiceTemplate"]["tpl-service-csv-values"]["enable_perfdata"]': true
