apiVersion: grizzly.grafana.com/v1alpha1
kind: Dashboard
metadata:
  folder: linuxfabrik-monitoring-plugins
  name: ping
spec:
  schemaVersion: 2023041201
  tags:
    - Linuxfabrik
    - Grizzly
    - static
  time:
    from: now-90d
    to: now
  timepicker:
    hidden: false
    refresh_intervals:
    - 1m
  timezone: browser
  title: Ping
  uid: linuxfabrik-monitoring-plugins-ping
  editable: true
  liveNow: true
  refresh: 1m
  templating:
    list:
    - hide: 2
      label: Command
      name: command
      query: cmd-check-ping
      type: constant
    - label: Hostname
      name: hostname
      query: SHOW TAG VALUES FROM "cmd-check-ping" WITH KEY = "hostname"
      refresh: 1
      sort: 1
      type: query

  panels:

  - title: Ping - packet loss
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 0
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          lineInterpolation: smooth
          spanNulls: true
        decimals: 0
        max: 110
        min: 0
        unit: percent
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: packet_loss
      refId: packet_loss
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: metric
        operator: '='
        value: packet_loss


  - title: Ping - time
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 12
      y: 0
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          lineInterpolation: smooth
          spanNulls: true
        decimals: 1
        min: 0
        unit: s
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: time
      refId: time
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: metric
        operator: '='
        value: time


  - title: Ping - Packets
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 0
      y: 8
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          lineInterpolation: smooth
          spanNulls: true
        decimals: 0
        min: 0
        unit: short
        properties:
        - id: custom.hideFrom
          value:
            viz: true
      overrides:
      - __systemRef: hideSeriesFrom
        matcher:
          id: byNames
          options:
            mode: exclude
            names:
            - received
            - transmitted
            prefix: 'All except:'
        properties:
        - id: custom.hideFrom
          value:
            viz: true
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: checksum_corrupted
      refId: checksum_corrupted
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: metric
        operator: '='
        value: checksum_corrupted

    - alias: duplicates
      refId: duplicates
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: metric
        operator: '='
        value: duplicates

    - alias: errors
      refId: errors
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: metric
        operator: '='
        value: errors

    - alias: received
      refId: received
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: metric
        operator: '='
        value: received

    - alias: transmitted
      refId: transmitted
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: metric
        operator: '='
        value: transmitted


  - title: Ping - rtt
    type: timeseries
    gridPos:
      h: 8
      w: 12
      x: 12
      y: 8
    fieldConfig:
      defaults:
        color:
          mode: palette-classic
        custom:
          lineInterpolation: smooth
          spanNulls: true
        decimals: 1
        min: 0
        unit: s
      overrides:
      - __systemRef: hideSeriesFrom
        matcher:
          id: byNames
          options:
            mode: exclude
            names:
            - rtt_avg
            - rtt_mdev
            prefix: 'All except:'
        properties:
        - id: custom.hideFrom
          value:
            viz: true
    options:
      legend:
        calcs:
        - first
        - min
        - mean
        - max
        - last
        displayMode: table
        placement: bottom
        showLegend: true
      tooltip:
        mode: multi
        sort: none

    targets:

    - alias: rtt_avg
      refId: rtt_avg
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: metric
        operator: '='
        value: rtt_avg

    - alias: rtt_max
      refId: rtt_max
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: metric
        operator: '='
        value: rtt_max

    - alias: rtt_mdev
      refId: rtt_mdev
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: metric
        operator: '='
        value: rtt_mdev

    - alias: rtt_min
      refId: rtt_min
      groupBy:
      - params:
        - $interval
        type: time
      measurement: $command
      resultFormat: time_series
      select:
      - - params:
          - value
          type: field
        - params: []
          type: mean
      tags:
      - key: hostname
        operator: '='
        value: $hostname
      - condition: AND
        key: metric
        operator: '='
        value: rtt_min


